### ISSUE TITLE
Button 컴포넌트 fullwidth prop 추가 제안

### ISSUE THREAD

**Issue by jjunyjjuny** [depromeet/ohmebddeng-frontend#12]
@eunsukimme 

버튼 컴포넌트의 `width`를 `100%`로 하는 일이 잦을 거 같아서, (사실 거의 대부분?) `rounded` 처럼 `fullWidth` 속성도 추가하면 좋을 거 같습니다.

사실 제가 해도 되는데 다른 사람의 코드를 말 없이 수정하는건 안 될거 같아서 일단 요렇게 이슈로 남겨보는데 원래 이러케 하는게 맞나? 모르겠네요 희희.. 그냥 한 번 이슈 남겨봤습니다..

**Comment by eunsukimme** [comment]
오 네 저는 좋은 것 같습니다~ 저희가 쓰기 편한게 제일 좋은 방식이죠.
